### ISSUE TITLE
add bottom tool bar support

### ISSUE THREAD

**Issue by murali-reddy** [cloudnativelabs/kube-shell#3]
tool bar need to have below options

- toggle inline help with dropped down list
- info on current kubeconfig context used, namespace
- vi/emacs mode
- exit 

refer to saws/aws-shell for bottom toolbar reference

**Comment by fhemberger** [comment]
Would be great to have a hokey to quickly switch clusters, users and namespaces

**Comment by murali-reddy** [comment]
Thanks @fhemberger for the feedback. makes lot of sense. AFAIK, python prompt kit toolbar can not have drop down/up many so we will have to use function keys to toggle between the clusters/users/namespace. we will incorporate the feedback in best way possible.
