### ISSUE TITLE
how can I switch multiple clusters？

### ISSUE THREAD

**Issue by arrowfeng** [cloudnativelabs/kube-shell#65]
I have two clusters，how can I  press F4 to switch other cluster？

**Comment by mabushey** [comment]
I'm running kube-shell in docker: `solsson/kube-shell`. `F9` Toggles In-line help between `ON` and `OFF`, `F10` exits, however `F4` and `F5` do not appear mapped correctly as they do nothing. I typically use `kubectx` to change the cluster, and `kubens` to change the active namespace. In newer kubectl I think for example `kubectx` could be named `kubectl-ctx` to become a plugin accessible via `kubectl ctx ...`

**Comment by arrowfeng** [comment]
thank you.
